### ISSUE TITLE
account verification mechanism

### ISSUE THREAD

**Issue by jann7790** [alaaalbayed/Facebook-Account-creator#1]
Hi, I'm build up instagram account creator, but when I create too much account, Instagram would ask me to use the phone verification.
Does that happened on facebook?? or using mail verification is just enough.

**Comment by alaaalbayed** [comment]
welcome bro! , i think u need proxy u can import proxies using this command
please check this link ! :
https://stackoverflow.com/questions/17082425/running-selenium-webdriver-with-a-proxy-in-python
if u need anything plz contact me again i will be happy to help u.

>
